### ISSUE TITLE
Version 2.0 Epic

### ISSUE THREAD

**Issue by jmassardo** [jmassardo/issues-to-totango#11]
- [ ] Label issue with Totango touchpoint ID
- [ ] Add `type` option to allow creation of tasks
- [ ] Assign task to `assignees` of issue
- [ ] If you close an issue, close the task in Totango
- [ ] If you update an issue, it should update either the touchpoint or the task
- [ ] #8 
- [ ] If you set a `priority` label, that priority should flow to the task
- [ ] What happens if the assignee is not a Hubber? Should we drop them? Should we specify the CSA/M and use that as the assignee?
