### ISSUE TITLE
Updated documentation (in this repo and in the internal docs)

### ISSUE THREAD

**Issue by jmassardo** [jmassardo/issues-to-totango#19]
```[tasklist]
### Tasks
- [x] Update with examples directly in main README for this repo
- [x] Validate all docs are up to date for this repo
- [x] Update [github/totango](https://github.com/github/Totango/blob/main/How-to-Totango/Integrations%20%26%20Data/Issues%20to%20Totango%20Action.md)
```
