### ISSUE TITLE
New tasks created in totango should flow into GitHub

### ISSUE THREAD

**Issue by jmassardo** [jmassardo/issues-to-totango#66]
```[tasklist]
### Tasks
- [ ] The action should run on a scheduled task
- [ ] The action should accept a URL for a target project board
- [ ] The action should create draft issues on the specified project board
- [ ] The assignee from the Totango task should flow to the issue
```
